# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
            ],
        ),
    ]
